# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85e0921b6dca2d43308344d994440ac32c04b4a978b70ac28c40740900ee74f3c97b5d58f089207d19c7012b19c09fee4bb27085b2999eed7f94f09e130a09d2

test:
  secret_key_base: 465441a85f0faa2389531d8d401a45ebf1c44df95ca39be3522f64388478d3829d7ba396d7cd5e7c79f36b236efa94daeef769d661af12ac274bfc534b9dfd91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
